[features]
seeds = false
skip-lint = false
[programs.devnet]
solana6551 = "CbkGxYsZct6iaLY6n13NUX7D4gvS2qqRcDBKFgr2JCeQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
